context:
  version: "0.1.1"
  python_min: "3.13"

package:
  name: pixi-skills
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/32/2c/1bc8b5cbdb4cec736779e61c285e51579cccf5046291eb228a59f631d94a/pixi_skills-${{ version }}.tar.gz
  sha256: 526aa3e01bcc5b57d7f83267c9299d21991665fbef5d6828d1bc8f376cd19bcd

build:
  noarch: python
  python:
    entry_points:
      - pixi-skills=pixi_skills.cli:app
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - typer >=0.12
    - rich >=13
    - questionary >=2
    - pyyaml >=6

tests:
  - python:
      imports:
      - pixi_skills
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pixi-skills --help

about:
  homepage: https://github.com/pavelzw/pixi-skills
  summary: Manage coding agent skills using pixi
  description: |
    Manage and install coding agent skills across multiple LLM backends using pixi.

    pixi-skills discovers skills packaged in pixi environments and lets you install them into the configuration directories of various coding agents via symlinks.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://github.com/pavelzw/pixi-skills
  repository: https://github.com/pavelzw/pixi-skills

extra:
  recipe-maintainers:
    - pavelzw
